version: '3.9'
services:
  php-fpm:
    image: php:7.2-fpm
    volumes:
      - ./app:/var/www/html
    depends_on:
      mysql-db:
        condition: service_healthy
  
  apache-httpd:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
  
  mysql-db:
    image: mysql:8.0.36-debian
    volumes:
      - ./db/data-create.sql:/docker-entrypoint-initdb.d/data-create.sql
      - ./db/data-mods.sql:/docker-entrypoint-initdb.d/data-mods.sql
    env_file:
      - ./.env
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: projects 
    ports:
      - "3307:3306"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
  
  node:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      mysql-db:
        condition: service_healthy
        
  
    